name: CI - 6G-Valid8 Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python3 -m venv .venv
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8

    - name: Check Python Path
      run: |
        echo "Current PYTHONPATH: $PYTHONPATH"
        python -c "import sys; print(sys.path)"

    - name: Set PYTHONPATH and run tests
      run: |
        export PYTHONPATH=$(pwd)/backend
        echo "PYTHONPATH=$PYTHONPATH"

    - name: Run pytest
      run: |
        source .venv/bin/activate
        pytest -v > result.log || tail -n 10 result.log


    - name: Upload test results (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: result.log
