name: CI - 6G-Valid8 Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set PYTHONPATH to backend for proper imports
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/backend" >> $GITHUB_ENV

      # Step 5: Verify the working directory (optional)
      - name: Verify Working Directory
        run: echo "Current directory: $(pwd)"

      # Step 6: Run tests with pytest
      - name: Run tests with pytest
        run: |
          export PYTHONPATH=$(pwd)/backend
          pytest --maxfail=1 --disable-warnings -q
