name: CI - 6G-Valid8 Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step: Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step: Check the directory structure (for debugging)
      - name: List directory contents
        run: ls -la

      # Step: Setup virtual environment
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      # Step: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
